//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeCo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corsi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Corsi()
        {
            this.Iscrizioni = new HashSet<Iscrizioni>();
            this.Lezioni = new HashSet<Lezioni>();
        }
    
        public int idCorso { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> dataInizio { get; set; }
        public Nullable<System.DateTime> dataFine { get; set; }
        public string descrizione { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Iscrizioni> Iscrizioni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lezioni> Lezioni { get; set; }
    }
}
