//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeCo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iscrizioni
    {
        public int idIscrizione { get; set; }
        public Nullable<int> fkCorso { get; set; }
        public string fkStudente { get; set; }
    
        public virtual Corsi Corsi { get; set; }
        public virtual Studenti Studenti { get; set; }
    }
}
