//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeCo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lezioni
    {
        public int idLezione { get; set; }
        public string nome { get; set; }
        public Nullable<int> durata { get; set; }
        public string descrizione { get; set; }
        public Nullable<int> fkCorso { get; set; }
    
        public virtual Corsi Corsi { get; set; }
    }
}
